//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplineModel
    {
        public string Roll_No { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public int Index { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual StudentModelLogin StudentLogin { get; set; }
    }
}
