//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAnswer
    {
        public int SAno { get; set; }
        public string Roll_No { get; set; }
        public string Answer { get; set; }
        public Nullable<int> Qno { get; set; }
        public Nullable<decimal> Mark_Obtained { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual StudentModelLogin StudentLogin { get; set; }
    }
}
