//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TotalMarks
    {
        public string Roll_No { get; set; }
        public Nullable<decimal> TotalMark { get; set; }
    }
}
